/* eslint-disable react/prop-types */
import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { setApiLanguage } from '../api/client';

const LANG_STORAGE_KEY = 'lang';

const translations = {
  en: {
    appName: 'Black Fox',
    appSubtitle: 'Clothing Factory Management',
    main: 'Main',
    operations: 'Operations',
    people: 'People',
    business: 'Business',
    dashboard: 'Dashboard',
    production: 'Production',
    createOrder: 'Create Order',
    sorting: 'Sorting (فرز)',
    finalPhase: 'Final Phase',
    prodReport: 'Production Report',
    productionPipeline: 'Pipeline Kanban',
    productionPipelineSubtitle: 'Drag and drop production orders across stages',
    noOrders: 'No orders in this stage',
    products: 'Products',
    inventory: 'Inventory',
    employees: 'Employees',
    attendance: 'Attendance',
    payroll: 'Payroll',
    loans: 'Loans',
    sales: 'Sales',
    customers: 'Customers',
    reports: 'Reports',
    signIn: 'Sign in',
    welcomeBack: 'Welcome back. Enter your credentials to continue.',
    loginHint: 'Factory Management',
    dashboardDate: (date) => date,
    activeOrders: 'Active orders',
    currentlyOpen: 'Currently open',
    revenue: 'Revenue',
    customerPaymentsThisMonth: 'Customer payments this month',
    moneySpent: 'Money spent',
    paidPayrollThisMonth: 'Paid payroll this month',
    netAfterPayroll: 'Net after payroll',
    revenueMinusPaidSalary: 'Revenue minus paid salary',
    productionByStatus: 'Production by status',
    noProductionDataYet: 'No production data yet',
    quickStats: 'Quick stats',
    lowStockItems: 'Low stock items',
    activeEmployees: 'Active employees',
    paidPayrollThisMonthShort: 'Paid payroll this month',
    selectLanguage: 'Language',
    english: 'EN',
    arabic: 'العربية',
    unit: 'Unit',
    email: 'Email',
    phone: 'Phone',
    city: 'City',
    country: 'Country',
    address: 'Address',
    since: 'Since',
    payment: 'Payment',
    new: 'New',
    confirmed: 'Confirmed',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    view: 'View',
    ledger: 'Ledger',
    close: 'Close',
    delete: 'Delete',
    addItem: '+ Add item',
    remove: 'Remove',
    generate: '+ Generate Payroll',
    manageRawMaterials: 'Manage raw materials and stock levels',
    material: 'Material',
    category: 'Category',
    qty: 'Qty',
    minQty: 'Min qty',
    unitCost: 'Unit cost',
    supplier: 'Supplier',
    status: 'Status',
    addMaterial: 'Add material',
    editMaterial: 'Edit material',
    save: 'Save',
    cancel: 'Cancel',
    saving: 'Saving…',
    lowStock: 'Low stock',
    ok: 'OK',
    edit: 'Edit',
    del: 'Del',
    nameRequired: 'Name is required.',
    unitRequired: 'Unit is required.',
    nonNegativeQuantity: 'Quantity must be a non-negative number.',
    nonNegativeMinQuantity: 'Min quantity must be a non-negative number.',
    failedSaveMaterial: 'Failed to save material.',
    deleteMaterial: 'Delete this material?',
    materialUpdated: 'Material updated!',
    materialAdded: 'Material added!',
    addCustomer: 'Add customer',
    customerNameRequired: 'Customer name is required.',
    validEmailRequired: 'A valid email is required.',
    phoneRequired: 'Phone is required.',
    customerAdded: 'Customer added successfully!',
    failedAddCustomer: 'Failed to add customer.',
    customerLedger: 'Customer ledger',
    productsTaken: 'Products taken',
    totalOrdered: 'Total ordered',
    totalPaid: 'Total paid',
    remaining: 'Remaining',
    paymentDate: 'Payment date',
    amount: 'Amount',
    notes: 'Notes',
    addPayment: 'Add payment',
    evidence: 'Evidence',
    viewFile: 'View file',
    noOrdersYet: 'No orders for this customer yet.',
    noPaymentsYet: 'No payments recorded yet.',
    manageClientAccounts: 'Manage your client accounts',
    savePolicy: 'Save Policy',
    attendancePayrollPolicy: 'Attendance & Payroll Policy',
    configurePolicy: 'Configure grace period, multipliers, and weekly payment estimate',
    lateGraceMinutes: 'Late Grace Minutes',
    regularOvertimeMultiplier: 'Regular Overtime Multiplier',
    vacationWeekendMultiplier: 'Vacation/Weekend Multiplier',
    weeksPerMonth: 'Weeks Per Month',
    lateGraceRange: 'Late grace minutes must be between 0 and 180.',
    overtimeRange: 'Overtime multiplier must be between 1 and 5.',
    vacationRange: 'Vacation multiplier must be between 0 and 5.',
    weeksRange: 'Weeks per month must be between 1 and 6.',
    settingsSaved: 'Settings saved successfully. New values apply immediately.',
    failedLoadSettings: 'Failed to load settings',
    failedSaveSettings: 'Failed to save settings',
    createProductionOrder: 'Create Production Order',
    inputPhaseMaterialConsumption: 'Input phase + material consumption',
    modelNumber: 'Model Number',
    productNumber: 'Product Number',
    productName: 'Product name',
    productNumberRequired: 'Product number is required.',
    productNameRequired: 'Product name is required.',
    productNumberPlaceholder: 'e.g. 6001, 6002',
    selectProductRequired: 'Please select a product.',
    createOrderSubtitle: 'Select product name and enter the order number (e.g. 6001, 6002)',
    productNamePlaceholder: 'Product name',
    sortingSubtitle: 'Record sorting quantity for each production order',
    sortingSaved: 'Sorting phase saved.',
    exitPermissionInManage: 'Print exit permission from Manage Orders.',
    printExitPermission: 'Exit Permission',
    reprintExitPermission: 'Reprint Exit Permission',
    printing: 'Printing…',
    printFailed: 'Failed to print exit permission.',
    manageOrders: 'Manage Orders',
    manageOrdersSubtitle: 'View orders, print exit permission after sorting, or cancel with password',
    cancelOrder: 'Cancel / Delete',
    cancelOrderTitle: 'Cancel Production Order?',
    cancelOrderWarning: 'This will permanently delete the order and restore deducted materials. Finished product stock will be reversed if applicable.',
    confirmPassword: 'Enter your password to confirm',
    passwordRequired: 'Password is required.',
    orderDeleted: 'Order cancelled and deleted successfully.',
    allStatuses: 'All statuses',
    plannedQuantity: 'Planned Quantity',
    materials: 'Materials',
    qtyUsed: 'Qty used',
    lastCreatedOrder: 'Last Created Order',
    phase: 'Phase',
    quantity: 'Quantity',
    trackManufacturingOrders: 'Track manufacturing orders and progress',
    newOrder: '+ New order',
    newProductionOrder: 'New production order',
    assignTo: 'Assign to',
    startDate: 'Start date',
    dueDate: 'Due date',
    newOrderSaved: 'Creating…',
    createOrderButton: 'Create order',
    updateProgress: 'Update progress',
    orderedQuantity: 'Ordered quantity',
    finishedQuantity: 'Finished quantity',
    saveProgress: 'Save progress',
    progress: 'Progress',
    productionTrackingReport: 'Production Tracking Report',
    comparePhases: 'Compare quantities across Input, Sorting, and Final phases',
    selectProductionOrder: 'Select Production Order',
    chooseOrder: 'Choose order',
    metric: 'Metric',
    value: 'Value',
    phaseDetails: 'Phase Details',
    phaseQuantityChart: 'Phase Quantity Chart',
    alerts: 'Alerts',
    warningLoss: 'Warning: Loss exceeds 10% (HIGH_LOSS alert)',
    efficiency: 'Efficiency',
    loss: 'Loss',
    input: 'Input',
    final: 'Final',
    totalLoss: 'Total Loss',
    lossPercentage: 'Loss Percentage',
    trackDailyAttendance: 'Track daily employee attendance',
    logAttendance: 'Log attendance',
    daysPresent: 'Days present',
    daysLate: 'Days late',
    daysAbsent: 'Days absent',
    totalHours: 'Total hours',
    back: 'Back',
    monthlyCalendar: 'Monthly calendar',
    noRecordsForMonth: 'No attendance records for this month.',
    noEmployeesFound: 'No employees found.',
    employee: 'Employee',
    present: 'Present',
    late: 'Late',
    absent: 'Absent',
    deviceNo: 'Device No',
    attendanceRate: 'Attendance rate',
    checkIn: 'Check in',
    checkOut: 'Check out',
    hoursWorked: 'Hours worked',
    earlyLeave: 'Early leave',
    overtime: 'Overtime',
    date: 'Date',
    statusLabel: 'Status',
    selectEmployee: 'Select employee',
    selectMaterial: 'Select material',
    logAttendanceButton: '+ Log attendance',
    manageCustomerOrders: 'Manage customer orders and invoices',
    newSalesOrder: 'New sales order',
    orderItems: 'Order items',
    qtyPlaceholder: 'Qty',
    unitPricePlaceholder: 'Unit price',
    create: 'Create',
    customerBalance: 'Customer balance',
    clear: 'Clear',
    orderStatus: 'Order status',
    weeklyPayroll: 'Manage weekly payroll (Saturday to Friday) and payments',
    weekStartSaturday: 'Week start (Saturday)',
    generatePayroll: 'Generate payroll',
    payrollBreakdown: 'Payroll breakdown',
    markAsPaid: 'Mark as paid?',
    markPaid: 'Mark paid',
    week: 'Week',
    role: 'Role',
    base: 'Base',
    bonus: 'Bonus',
    deductions: 'Deductions',
    netSalary: 'Net salary',
    weeklyPay: 'Weekly pay',
    breakdown: 'Breakdown',
    autoBonus: 'Auto bonus',
    autoDeductions: 'Auto deductions',
    manualBonus: 'Manual bonus',
    manualDeductions: 'Manual deductions',
    clearManual: 'Clear manual',
    confirmClearManual: 'Clear manual bonus and deductions for this employee?',
    lateMinutes: 'Late minutes',
    lateWeightedMinutes: 'Late weighted minutes',
    earlyLeaveMinutes: 'Early leave minutes',
    regularOvertime: 'Regular overtime',
    weekendWorkOvertime: 'Weekend work overtime',
    totalOvertime: 'Total overtime',
    absentDays: 'Absent days',
    halfDays: 'Half days',
    inferredAbsentDays: 'Inferred absent days',
    weeklyPaymentEstimate: 'Weekly payment estimate',
    lateDeduction: 'Late',
    weighted: 'weighted',
    days: 'day(s)',
    halfDay: 'Half day',
    hrBonus: 'HR bonus',
    hrPenalty: 'HR penalty',
    hrOvertime: 'HR overtime',
    noAdjustments: 'No deductions or bonuses this week.',
    machine: 'Machine',
    partnerFactory: 'Partner Factory',
    selectPartnerFactory: 'Select partner factory',
    addPartnerFactory: '+ Add partner factory',
    partnerFactoryName: 'Factory name',
    partnerFactoryNameRequired: 'Partner factory name is required.',
    partnerFactoryCreateFailed: 'Failed to add partner factory.',
    contactPerson: 'Contact person',
    machineOrPartnerFactory: 'Machine / Partner Factory',
    duration: 'Duration',
    deleteOrder: 'Delete Production Order?',
    deleteWarning: 'This will delete the production order and restore all deducted inventory. This action cannot be undone.',
    deleteFailed: 'Failed to delete order',
    deleteFailedCycleStarted: 'Cannot delete order - sorting or final phase has already started. You can only delete new orders.',
    deleting: 'Deleting...',
    outsourcing: 'Outsourcing',
    outsourcingPhase: 'Outsourcing Phase',
    outsourcingSubtitle: 'Send items to an external partner factory for specialized processing',
    outsourcingQty: 'Outsourcing Quantity',
    outsourcingQtyError: 'Outsourcing quantity must be a non-negative integer.',
    outsourcingSaved: 'Outsourcing phase saved.',
    outsourcingFailed: 'Failed to save outsourcing phase.',
    outsourcingSaveBtn: 'Save Outsourcing Phase',
    stageEfficiency: 'Stage Efficiency',
    totalQty: 'Total Qty',
    avgLoss: 'Avg Loss %',
    currentOrders: 'Current Orders',
    adjust: 'Adjust',
    adjustPayroll: 'Adjust Payroll',
    failedAdjustPayroll: 'Failed to adjust payroll.',
    loanDeduction: 'Loan deduction',
    weekDateRange: 'Week date range',
    from: 'from',
    to: 'to',
    saturday: 'Saturday',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    confirmDeleteWeekPayroll: "Are you sure you want to delete this week's payroll? This will also revert any loan deductions applied for this week.",
    payrollDeleteFailed: 'Failed to delete payroll week.',
    exportPDF: 'Export PDF',
    payrollExportFailed: 'Failed to export payroll to PDF.',
    totalNet: 'Total Net',
    department: 'Department',
    editPayment: 'Edit Payment',
    deletePayment: 'Delete Payment',
    deletePaymentTitle: 'Delete Payment',
    confirmDeletePaymentMsg: 'Are you sure you want to delete this payment of',
    deletePaymentWarning: 'This will revert invoice allocations and recalculate the customer ledger balance.',
    saveChanges: 'Save changes',
    newEvidence: 'Update Evidence (optional)',
    currentFile: 'Current file',
    paymentMethod: 'Payment method',
    referenceNumber: 'Reference #',
    validAmountRequired: 'Please enter a valid amount greater than 0',
    notesPlaceholder: 'Payment notes / description',
    paymentUpdatedSuccess: 'Payment updated successfully',
    paymentDeletedSuccess: 'Payment deleted successfully',
    model: 'Model',
    color: 'Color',
    pcs: 'pcs',
    unitPrice: 'Unit price',
    lineTotal: 'Total',
    currency: 'EGP',
    balanceDue: 'Owes',
    balanceCredit: 'In credit',
    tabStatement: 'Account statement',
    tabDeliveries: 'Deliveries',
    tabPayments: 'Payments',
    fromDate: 'From',
    toDate: 'To',
    allPeriods: 'All periods',
    printStatement: 'Print statement',
    openingBalance: 'Opening balance',
    closingBalance: 'Closing balance',
    stmtDate: 'Date',
    stmtDescription: 'Description',
    stmtDebit: 'Charged',
    stmtCredit: 'Paid',
    stmtBalance: 'Balance',
    typeDelivery: 'Delivery',
    typePayment: 'Payment',
    periodTotal: 'Period total',
    noMovements: 'No movements in this period',
    payPaid: 'Paid',
    payPending: 'Unpaid',
    payPartial: 'Partially paid',
    paymentHistory: 'Payment history',
    searchCustomers: 'Search by name, phone or city...',
    emp_colName: 'Name',
    emp_department: 'Department',
    emp_colDeviceId: 'Device ID',
    emp_colRole: 'Role',
    emp_shift: 'Shift',
    emp_colWeekend: 'Weekend',
    emp_colWeeklySalary: 'Weekly Salary',
    emp_status: 'Status',
    emp_edit: 'Edit',
    emp_title: 'Employees',
    emp_subtitle: 'Manage your factory workforce',
    emp_addBtn: '+ Add employee',
    emp_search: 'Search by name, department, role, phone, or device ID...',
    emp_fullName: 'Full name',
    emp_phone: 'Phone',
    emp_selectDepartment: 'Select department',
    emp_rolePosition: 'Role / Position',
    emp_deviceUserId: 'Device user ID',
    emp_shift_morning: 'Morning',
    emp_shift_evening: 'Evening',
    emp_shift_night: 'Night',
    emp_shiftStart: 'Shift start',
    emp_shiftEnd: 'Shift end',
    emp_weekendDays: 'Weekend days',
    emp_status_active: 'Active',
    emp_status_inactive: 'Inactive',
    emp_salaryReason: 'Reason for salary change (optional)',
    emp_salaryReasonPh: 'e.g. Annual Raise, Promotion',
    emp_hireDate: 'Hire date',
    emp_cancel: 'Cancel',
    emp_daySun: 'Sun',
    emp_dayMon: 'Mon',
    emp_dayTue: 'Tue',
    emp_dayWed: 'Wed',
    emp_dayThu: 'Thu',
    emp_dayFri: 'Fri',
    emp_daySat: 'Sat',
    emp_none: 'None',
    emp_errName: 'Name is required.',
    emp_errDepartment: 'Department is required.',
    emp_errShift: 'Shift is required.',
    emp_errShiftStart: 'Shift start is required.',
    emp_errShiftEnd: 'Shift end is required.',
    emp_errSalary: 'Salary must be a non-negative number.',
    emp_errSave: 'Failed to save employee.',
    emp_confirmTerminate: 'Terminate this employee? Their historical payroll and attendance data will be preserved.',
    emp_status_terminated: 'terminated',
    emp_terminate: 'Del',
    emp_editEmployee: 'Edit employee',
    emp_addEmployee: 'Add employee',
    emp_salary: 'Salary',
    emp_saving: 'Saving…',
    emp_save: 'Save',
    att_view: 'View',
    att_checkIn: 'Check in',
    att_checkOut: 'Check out',
    att_hours: 'Hours',
    att_late: 'Late',
    att_earlyLeave: 'Early leave',
    att_overtime: 'Overtime',
    att_logBtn: '+ Log attendance',
    att_daysPresent: 'Days present',
    att_daysLate: 'Days late',
    att_daysAbsent: 'Days absent',
    att_totalHours: 'Total hours',
    att_filterRange: 'Filter by date range:',
    att_to: 'to',
    att_thisWeek: 'This Week',
    att_fullMonth: 'Full Month',
    att_search: 'Search by employee name or device ID...',
    att_back: '← Back',
    att_noRecords: 'No attendance records for this period.',
    att_monthlyCalendar: 'MONTHLY CALENDAR',
    att_noEmployees: 'No employees found.',
    att_logTitle: 'Log attendance',
    att_employee: 'Employee',
    att_selectEmployee: 'Select employee',
    att_date: 'Date',
    att_status: 'Status',
    att_hoursWorked: 'Hours worked',
    att_lateMin: 'Late (minutes)',
    att_earlyMin: 'Early leave (minutes)',
    att_overtimeMin: 'Overtime (minutes)',
    att_notes: 'Notes',
    att_cancel: 'Cancel',
    todayCheckInOut: 'Today (In / Out)',
    att_status_present: 'present',
    att_status_late: 'late',
    att_status_absent: 'absent',
    'att_status_half-day': 'half-day',
    att_noRecord: 'no record',
    att_inferredAbsence: 'Inferred absence (missing attendance log)',
    att_title: 'Attendance',
    att_subtitle: 'track daily employee attendance',
    loan_employee: 'Employee',
    loan_status: 'Status',
    loan_created: 'Created',
    loan_actions: 'Actions',
    loan_edit: 'Edit / Adjust',
    loan_title: 'Loans',
    loan_subtitle: 'Create and track employee loans and repayments',
    loan_showFinished: 'Show finished loans',
    loan_addBtn: '+ Add loan',
    loan_selectEmployee: 'Select employee',
    loan_principalAmount: 'Principal amount',
    loan_remainingAmount: 'Remaining amount',
    loan_installmentAmount: 'Monthly installment',
    loan_active: 'Active',
    loan_closed: 'Closed',
    loan_cancel: 'Cancel',
    loan_errEmployee: 'Please select an employee.',
    loan_errPrincipal: 'Principal amount must be greater than zero.',
    loan_errInstallment: 'Monthly installment must be greater than zero.',
    loan_errRemaining: 'Remaining amount must be a non-negative number.',
    loan_errUpdate: 'Failed to update loan.',
    loan_errCreate: 'Failed to create loan.',
    loan_principal: 'Principal',
    loan_remaining: 'Remaining',
    loan_installment: 'Installment',
    loan_finished: 'Finished',
    loan_editTitle: 'Edit / Adjust loan',
    loan_addTitle: 'Add loan',
    loan_saving: 'Saving…',
    loan_update: 'Update',
    loan_save: 'Save',
    nav_logout: 'Logout',
    accounting: 'Accounting',
    auth_email: 'Email',
    auth_password: 'Password',
    prod_search: 'Search by name or description...',
    nonNegativePrice: 'Price must be a non-negative number.',
    productUpdated: 'Product updated!',
    productAdded: 'Product added!',
    failedSaveProduct: 'Failed to save product.',
    deleteProduct: 'Delete this product?',
    product: 'Product',
    description: 'Description',
    defaultPrice: 'Default Price',
    manageProductCatalog: 'Manage product names for production and sales',
    addProduct: '+ Add product',
    editProduct: 'Edit product',
    cust_methodPh: 'e.g. cash, bank, check',
    cust_refPh: 'Ref / Check number',
    cust_name: 'Name',
    pay_employees: 'employees',
    pay_more: 'more',
    pay_employeePayrolls: 'employee payrolls',
    pay_vs: 'vs',
    selectWeekStart: 'Please select a week start date.',
    payrollPartialFail: 'Payroll generated with some failures',
    payrollGenerated: 'Payroll generated for',
    payrollGeneratedOk: 'Payroll generated.',
    payrollGenerateFailed: 'Failed to generate payroll.',
    payrollPayFailed: 'Failed to mark payroll as paid.',
    payrollPayWeekFailed: 'Failed to mark week as paid.',
    paid: 'Paid',
    pending: 'Pending',
    recalcDriftHint: 'Recalculated total differs from the paid amount',
    all: 'All',
    searchByName: 'Search by name…',
    payrollTruncated: 'Showing the most recent records only. Narrow the date range to see everything in range.',
    noPayrollMatch: 'No payroll records match the current filters.',
    noPayrollYet: 'No payroll generated yet. Use "+ Generate" to create the first weekly payroll.',
    open: 'Open',
    weekDate: 'Week date',
    weeklyPayrollHint: 'Payroll weeks run Saturday to Friday. The selected date is mapped to that week, and salary is calculated from attendance within the week. Per-employee bonuses and deductions can be set afterwards with the "Adjust" button on each row.',
    sal_search: 'Search by order number, customer, status, or payment status...',
    sal_orderNo: 'Order #',
    sal_selectCustomer: 'Select customer',
    sal_pay_paid: 'paid',
    sal_pay_invoiced: 'invoiced',
    sal_pay_partially_paid: 'partially paid',
    sal_pay_pending: 'pending',
    orderNumber: 'Order Number',
    total: 'Total',
    defaultColor: 'Default',
    productionMetrics: 'PRODUCTION METRICS',
    inputQty: 'Input Quantity',
    sortingQty: 'Sorting Quantity',
    finalQty: 'Final Quantity',
    selectCustomer: 'Please select a customer.',
    orderItemsRequired: 'Add at least one valid production order with a unit price.',
    noValidItems: 'No valid items found in the selected orders.',
    createOrderFailed: 'Failed to create order.',
    updateStatusFailed: 'Failed to update status.',
    details: 'Details',
    selectOrder: 'Select Order',
    addOrder: '+ Add order',
    orderDetails: 'Order Details',
    failedToLoadOrderDetails: 'Failed to load order details',
    att_hUnit: 'h',
    att_mUnit: 'm',
    noRecordsFound: 'No records found',
  },
  ar: {
    appName: 'بلاك فوكس',
    appSubtitle: 'إدارة مصنع الملابس',
    main: 'الرئيسية',
    operations: 'العمليات',
    people: 'الأفراد',
    business: 'الأعمال',
    dashboard: 'لوحة التحكم',
    production: 'الإنتاج',
    createOrder: 'إنشاء أمر',
    sorting: 'الفرز',
    finalPhase: 'المرحلة النهائية',
    prodReport: 'تقرير الإنتاج',
    productionPipeline: 'مراحل الإنتاج (كانبان)',
    productionPipelineSubtitle: 'سحب وإفلات أوامر الإنتاج بين المراحل',
    noOrders: 'لا توجد طلبات في هذه المرحلة',
    products: 'المنتجات',
    inventory: 'المخزون',
    employees: 'الموظفون',
    attendance: 'الحضور',
    payroll: 'الرواتب',
    loans: 'القروض',
    sales: 'المبيعات',
    customers: 'العملاء',
    reports: 'التقارير',
    signIn: 'تسجيل الدخول',
    welcomeBack: 'مرحباً بعودتك. أدخل بياناتك للمتابعة.',
    loginHint: 'إدارة المصنع',
    dashboardDate: (date) => date,
    activeOrders: 'الطلبات النشطة',
    currentlyOpen: 'المفتوحة حالياً',
    revenue: 'الإيرادات',
    customerPaymentsThisMonth: 'مدفوعات العملاء هذا الشهر',
    moneySpent: 'المصروف',
    paidPayrollThisMonth: 'الرواتب المدفوعة هذا الشهر',
    netAfterPayroll: 'الصافي بعد الرواتب',
    revenueMinusPaidSalary: 'الإيرادات ناقص الرواتب المدفوعة',
    productionByStatus: 'الإنتاج حسب الحالة',
    noProductionDataYet: 'لا توجد بيانات إنتاج بعد',
    quickStats: 'إحصاءات سريعة',
    lowStockItems: 'العناصر منخفضة المخزون',
    activeEmployees: 'الموظفون النشطون',
    paidPayrollThisMonthShort: 'الرواتب المدفوعة هذا الشهر',
    selectLanguage: 'اللغة',
    english: 'EN',
    arabic: 'العربية',
    unit: 'الوحدة',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    city: 'المدينة',
    country: 'الدولة',
    address: 'العنوان',
    since: 'منذ',
    payment: 'الدفع',
    new: 'جديد',
    confirmed: 'مؤكد',
    shipped: 'تم الشحن',
    delivered: 'تم التسليم',
    cancelled: 'ملغي',
    view: 'عرض',
    ledger: 'كشف الحساب',
    close: 'إغلاق',
    delete: 'حذف',
    addItem: '+ إضافة عنصر',
    remove: 'إزالة',
    generate: '+ إعداد كشف جديد',
    manageRawMaterials: 'إدارة المواد الخام ومستويات المخزون',
    C: 'المادة',
    category: 'الفئة',
    qty: 'الكمية',
    minQty: 'الحد الأدنى',
    unitCost: 'تكلفة الوحدة',
    supplier: 'المورّد',
    status: 'الحالة',
    addMaterial: 'إضافة مادة',
    editMaterial: 'تعديل مادة',
    save: 'حفظ',
    cancel: 'إلغاء',
    saving: 'جارٍ الحفظ…',
    lowStock: 'مخزون منخفض',
    ok: 'ممتاز',
    edit: 'تعديل',
    del: 'حذف',
    nameRequired: 'الاسم مطلوب.',
    unitRequired: 'الوحدة مطلوبة.',
    nonNegativeQuantity: 'يجب أن تكون الكمية رقماً غير سالب.',
    nonNegativeMinQuantity: 'يجب أن يكون الحد الأدنى رقماً غير سالب.',
    failedSaveMaterial: 'فشل حفظ المادة.',
    deleteMaterial: 'حذف هذه المادة؟',
    materialUpdated: 'تم تحديث المادة!',
    materialAdded: 'تمت إضافة المادة!',
    addCustomer: 'إضافة عميل',
    customerNameRequired: 'اسم العميل مطلوب.',
    validEmailRequired: 'البريد الإلكتروني الصحيح مطلوب.',
    phoneRequired: 'رقم الهاتف مطلوب.',
    customerAdded: 'تمت إضافة العميل بنجاح!',
    failedAddCustomer: 'فشل إضافة العميل.',
    customerLedger: 'حساب العميل',
    productsTaken: 'المنتجات المسحوبة',
    totalOrdered: 'إجمالي الطلب',
    totalPaid: 'إجمالي المدفوع',
    remaining: 'المتبقي',
    paymentDate: 'تاريخ الدفع',
    amount: 'المبلغ',
    notes: 'ملاحظات',
    addPayment: 'إضافة دفعة',
    evidence: 'الإثبات',
    viewFile: 'عرض الملف',
    noOrdersYet: 'لا توجد طلبات لهذا العميل بعد.',
    noPaymentsYet: 'لم يتم تسجيل أي دفعات بعد.',
    manageClientAccounts: 'إدارة حسابات العملاء',
    savePolicy: 'حفظ السياسة',
    attendancePayrollPolicy: 'سياسة الحضور والرواتب',
    configurePolicy: 'تحديد فترة السماح والمعاملات وتقدير الدفع الأسبوعي',
    lateGraceMinutes: 'دقائق السماح للتأخير',
    regularOvertimeMultiplier: 'معامل الوقت الإضافي العادي',
    vacationWeekendMultiplier: 'معامل الإجازة/الويكند',
    weeksPerMonth: 'أسابيع الشهر',
    lateGraceRange: 'يجب أن تكون دقائق السماح بين 0 و180.',
    overtimeRange: 'يجب أن يكون معامل الوقت الإضافي بين 1 و5.',
    vacationRange: 'يجب أن يكون معامل الإجازة بين 0 و5.',
    weeksRange: 'يجب أن تكون أسابيع الشهر بين 1 و6.',
    settingsSaved: 'تم حفظ الإعدادات بنجاح. القيم الجديدة تطبق فوراً.',
    failedLoadSettings: 'فشل تحميل الإعدادات',
    failedSaveSettings: 'فشل حفظ الإعدادات',
    createProductionOrder: 'إنشاء أمر إنتاج',
    inputPhaseMaterialConsumption: 'مرحلة الإدخال + استهلاك المواد',
    modelNumber: 'رقم الموديل',
    productNumber: 'رقم المنتج',
    productName: 'اسم المنتج',
    productNumberRequired: 'رقم المنتج مطلوب.',
    productNameRequired: 'اسم المنتج مطلوب.',
    productNumberPlaceholder: 'مثال: 6001، 6002',
    selectProductRequired: 'يرجى اختيار المنتج.',
    createOrderSubtitle: 'اختر اسم المنتج وأدخل رقم الطلب (مثال: 6001، 6002)',
    productNamePlaceholder: 'اسم المنتج',
    sortingSubtitle: 'تسجيل كمية الفرز لكل أمر إنتاج',
    sortingSaved: 'تم حفظ مرحلة الفرز.',
    exitPermissionInManage: 'اطبع إذن الخروج من صفحة إدارة الطلبات.',
    printExitPermission: 'إذن الخروج',
    reprintExitPermission: 'إعادة طباعة إذن الخروج',
    printing: 'جاري الطباعة…',
    printFailed: 'فشل طباعة إذن الخروج.',
    manageOrders: 'إدارة الطلبات',
    manageOrdersSubtitle: 'عرض الطلبات وطباعة إذن الخروج بعد الفرز أو الإلغاء بكلمة المرور',
    cancelOrder: 'إلغاء / حذف',
    cancelOrderTitle: 'إلغاء أمر الإنتاج؟',
    cancelOrderWarning: 'سيؤدي هذا إلى حذف الطلب نهائياً واستعادة المواد المخصومة. سيتم عكس مخزون المنتجات النهائية إن وُجد.',
    confirmPassword: 'أدخل كلمة المرور للتأكيد',
    passwordRequired: 'كلمة المرور مطلوبة.',
    orderDeleted: 'تم إلغاء الطلب وحذفه بنجاح.',
    allStatuses: 'كل الحالات',
    plannedQuantity: 'الكمية المخططة',
    materials: 'المواد',
    qtyUsed: 'الكمية المستخدمة',
    lastCreatedOrder: 'آخر أمر تم إنشاؤه',
    phase: 'المرحلة',
    quantity: 'الكمية',
    trackManufacturingOrders: 'متابعة أوامر التصنيع والتقدم',
    newOrder: '+ أمر جديد',
    newProductionOrder: 'أمر إنتاج جديد',
    assignTo: 'إسناد إلى',
    startDate: 'تاريخ البداية',
    dueDate: 'تاريخ الاستحقاق',
    newOrderSaved: 'جارٍ الإنشاء…',
    createOrderButton: 'إنشاء الطلب',
    updateProgress: 'تحديث التقدم',
    orderedQuantity: 'الكمية المطلوبة',
    finishedQuantity: 'الكمية المنجزة',
    saveProgress: 'حفظ التقدم',
    progress: 'التقدم',
    productionTrackingReport: 'تقرير تتبع الإنتاج',
    comparePhases: 'مقارنة الكميات بين الإدخال والفرز والنهائي',
    selectProductionOrder: 'اختيار أمر الإنتاج',
    chooseOrder: 'اختيار الأمر',
    metric: 'المؤشر',
    value: 'القيمة',
    phaseDetails: 'تفاصيل المراحل',
    phaseQuantityChart: 'مخطط كميات المراحل',
    alerts: 'التنبيهات',
    warningLoss: 'تحذير: الفاقد يتجاوز 10% (تنبيه HIGH_LOSS)',
    efficiency: 'الكفاءة',
    loss: 'الفاقد',
    input: 'الإدخال',
    final: 'النهائي',
    totalLoss: 'إجمالي الفاقد',
    lossPercentage: 'نسبة الفاقد',
    trackDailyAttendance: 'متابعة حضور الموظفين يومياً',
    logAttendance: 'تسجيل الحضور',
    daysPresent: 'أيام الحضور',
    daysLate: 'أيام التأخير',
    daysAbsent: 'أيام الغياب',
    totalHours: 'إجمالي الساعات',
    back: 'رجوع',
    monthlyCalendar: 'التقويم الشهري',
    noRecordsForMonth: 'لا توجد سجلات حضور لهذا الشهر.',
    noEmployeesFound: 'لم يتم العثور على موظفين.',
    employee: 'الموظف',
    present: 'حاضر',
    late: 'متأخر',
    absent: 'غائب',
    deviceNo: 'رقم الجهاز',
    attendanceRate: 'نسبة الحضور',
    checkIn: 'الدخول',
    checkOut: 'الخروج',
    hoursWorked: 'ساعات العمل',
    earlyLeave: 'انصراف مبكر',
    overtime: 'إضافي',
    date: 'التاريخ',
    statusLabel: 'الحالة',
    selectEmployee: 'اختيار الموظف',
    logAttendanceButton: '+ تسجيل حضور',
    manageCustomerOrders: 'إدارة طلبات العملاء والفواتير',
    newSalesOrder: 'طلب مبيعات جديد',
    orderItems: 'عناصر الطلب',
    qtyPlaceholder: 'الكمية',
    unitPricePlaceholder: 'سعر الوحدة',
    create: 'إنشاء',
    customerBalance: 'رصيد العميل',
    clear: 'صفر',
    orderStatus: 'حالة الطلب',
    weeklyPayroll: 'إدارة الرواتب الأسبوعية (من السبت إلى الجمعة) والمدفوعات',
    weekStartSaturday: 'بداية الأسبوع (السبت)',
    generatePayroll: 'إعداد كشف الرواتب الأسبوعي',
    payrollBreakdown: 'تفصيل الراتب',
    markAsPaid: 'تحديد كمدفوع؟',
    markPaid: 'تم الدفع',
    week: 'الأسبوع',
    role: 'الوظيفة',
    base: 'الأساسي',
    bonus: 'البدل',
    deductions: 'الاستقطاعات',
    netSalary: 'صافي الراتب',
    weeklyPay: 'الأجر الأسبوعي',
    breakdown: 'التفصيل',
    autoBonus: 'سهر',
    autoDeductions: 'خصومات تأخير',
    manualBonus: 'بدل يدوي',
    manualDeductions: 'جزاءات',
    clearManual: 'مسح اليدوي',
    confirmClearManual: 'هل تريد مسح البدل اليدوي والجزاءات لهذا الموظف؟',
    lateMinutes: 'دقائق التأخير',
    lateWeightedMinutes: 'دقائق التأخير الموزونة',
    earlyLeaveMinutes: 'دقائق الانصراف المبكر',
    regularOvertime: 'الوقت الإضافي العادي',
    weekendWorkOvertime: 'إضافي نهاية الأسبوع',
    totalOvertime: 'إجمالي الإضافي',
    absentDays: 'أيام الغياب',
    halfDays: 'أنصاف الأيام',
    inferredAbsentDays: 'أيام غياب مستنتجة',
    weeklyPaymentEstimate: 'تقدير الدفع الأسبوعي',
    lateDeduction: 'التأخير',
    weighted: 'موزونة',
    days: 'يوم',
    halfDay: 'نصف يوم',
    hrBonus: 'مكافأة (موارد بشرية)',
    hrPenalty: 'جزاء (موارد بشرية)',
    hrOvertime: 'إضافي (موارد بشرية)',
    noAdjustments: 'لا يوجد خصومات أو مكافآت هذا الأسبوع.',
    machine: 'الماكينة',
    partnerFactory: 'المصنع الشريك',
    selectPartnerFactory: 'اختر المصنع الشريك',
    addPartnerFactory: '+ إضافة مصنع شريك',
    partnerFactoryName: 'اسم المصنع',
    partnerFactoryNameRequired: 'اسم المصنع الشريك مطلوب.',
    partnerFactoryCreateFailed: 'فشل إضافة المصنع الشريك.',
    contactPerson: 'جهة الاتصال',
    machineOrPartnerFactory: 'الماكينة / المصنع الشريك',
    duration: 'المدة',
    deleteOrder: 'حذف أمر الإنتاج؟',
    deleteWarning: 'سيؤدي هذا إلى حذف أمر الإنتاج واستعادة جميع المخزون المخصوم. لا يمكن التراجع عن هذا الإجراء.',
    deleteFailed: 'فشل حذف الطلب',
    deleteFailedCycleStarted: 'لا يمكن حذف الطلب - مرحلة الفرز أو النهائية قد بدأت بالفعل. يمكنك فقط حذف الطلبات الجديدة.',
    deleting: 'جاري الحذف...',
    outsourcing: 'التعهيد',
    outsourcingPhase: 'مرحلة التعهيد',
    outsourcingSubtitle: 'إرسال العناصر إلى مصنع شريك خارجي للمعالجة المتخصصة',
    outsourcingQty: 'كمية التعهيد',
    outsourcingQtyError: 'يجب أن تكون كمية التعهيد رقماً غير سالب.',
    outsourcingSaved: 'تم حفظ مرحلة التعهيد.',
    outsourcingFailed: 'فشل حفظ مرحلة التعهيد.',
    outsourcingSaveBtn: 'حفظ مرحلة التعهيد',
    stageEfficiency: 'كفاءة المراحل',
    totalQty: 'إجمالي الكمية',
    avgLoss: 'متوسط الفاقد %',
    currentOrders: 'الطلبات الحالية',
    adjust: 'تعديل',
    adjustPayroll: 'تعديل الراتب',
    failedAdjustPayroll: 'فشل تعديل الراتب.',
    loanDeduction: 'سلف',
    weekDateRange: 'فترة الأسبوع',
    from: 'من',
    to: 'إلى',
    saturday: 'السبت',
    sunday: 'الأحد',
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    confirmDeleteWeekPayroll: 'هل أنت متأكد من حذف راتب هذا الأسبوع؟ سيؤدي هذا أيضاً إلى إلغاء أي استقطاعات للقروض تم تطبيقها لهذا الأسبوع.',
    payrollDeleteFailed: 'فشل حذف راتب الأسبوع.',
    exportPDF: 'تصدير PDF',
    payrollExportFailed: 'فشل تصدير كشف الرواتب إلى PDF.',
    totalNet: 'إجمالي الصافي',
    department: 'القسم',
    editPayment: 'تعديل الدفعة',
    deletePayment: 'حذف الدفعة',
    deletePaymentTitle: 'حذف الدفعة',
    confirmDeletePaymentMsg: 'هل أنت متأكد من حذف هذه الدفعة بمبلغ',
    deletePaymentWarning: 'سيتم إلغاء التخصيص وإعادة احتساب رصيد العميل تلقائياً.',
    saveChanges: 'حفظ التعديلات',
    newEvidence: 'تحديث الإثبات (اختياري)',
    currentFile: 'الملف الحالي',
    paymentMethod: 'طريقة الدفع',
    referenceNumber: 'الرقم المرجعي',
    validAmountRequired: 'يرجى إدخال مبلغ صحيح أكبر من 0',
    notesPlaceholder: 'ملاحظات / وصف الدفعة',
    paymentUpdatedSuccess: 'تم تعديل الدفعة بنجاح',
    paymentDeletedSuccess: 'تم حذف الدفعة بنجاح',
    model: 'الموديل',
    color: 'اللون',
    pcs: 'ق',
    unitPrice: 'سعر القطعة',
    lineTotal: 'الإجمالي',
    currency: 'ج.م',
    balanceDue: 'عليه',
    balanceCredit: 'له',
    tabStatement: 'كشف الحساب',
    tabDeliveries: 'التسليمات',
    tabPayments: 'الدفعات',
    fromDate: 'من',
    toDate: 'إلى',
    allPeriods: 'كل الفترات',
    printStatement: 'طباعة كشف الحساب',
    openingBalance: 'رصيد أول المدة',
    closingBalance: 'الرصيد الختامي',
    stmtDate: 'التاريخ',
    stmtDescription: 'البيان',
    stmtDebit: 'عليه',
    stmtCredit: 'له',
    stmtBalance: 'الرصيد',
    typeDelivery: 'تسليم',
    typePayment: 'دفعة',
    periodTotal: 'إجمالي الفترة',
    noMovements: 'لا توجد حركات في هذه الفترة',
    payPaid: 'مدفوع',
    payPending: 'غير مدفوع',
    payPartial: 'مدفوع جزئياً',
    paymentHistory: 'سجل الدفعات',
    searchCustomers: 'ابحث بالاسم أو التليفون أو المدينة...',
    emp_colName: 'الاسم',
    emp_department: 'القسم',
    emp_colDeviceId: 'رقم البصمة',
    emp_colRole: 'الوظيفة',
    emp_shift: 'الوردية',
    emp_colWeekend: 'الإجازة',
    emp_colWeeklySalary: 'المرتب الأسبوعي',
    emp_status: 'الحالة',
    emp_edit: 'تعديل',
    emp_title: 'الموظفين',
    emp_subtitle: 'إدارة عمال المصنع',
    emp_addBtn: '+ إضافة موظف',
    emp_search: 'ابحث بالاسم أو القسم أو الوظيفة أو التليفون أو رقم البصمة...',
    emp_fullName: 'الاسم بالكامل',
    emp_phone: 'التليفون',
    emp_selectDepartment: 'اختار القسم',
    emp_rolePosition: 'الوظيفة',
    emp_deviceUserId: 'رقم البصمة في الجهاز',
    emp_shift_morning: 'صباحي',
    emp_shift_evening: 'مسائي',
    emp_shift_night: 'ليلي',
    emp_shiftStart: 'بداية الوردية',
    emp_shiftEnd: 'نهاية الوردية',
    emp_weekendDays: 'أيام الإجازة',
    emp_status_active: 'نشط',
    emp_status_inactive: 'موقوف',
    emp_salaryReason: 'سبب تغيير المرتب (اختياري)',
    emp_salaryReasonPh: 'مثال: زيادة سنوية، ترقية',
    emp_hireDate: 'تاريخ التعيين',
    emp_cancel: 'إلغاء',
    emp_daySun: 'الأحد',
    emp_dayMon: 'الاثنين',
    emp_dayTue: 'الثلاثاء',
    emp_dayWed: 'الأربعاء',
    emp_dayThu: 'الخميس',
    emp_dayFri: 'الجمعة',
    emp_daySat: 'السبت',
    emp_none: 'لا يوجد',
    emp_errName: 'الاسم مطلوب.',
    emp_errDepartment: 'القسم مطلوب.',
    emp_errShift: 'الوردية مطلوبة.',
    emp_errShiftStart: 'بداية الوردية مطلوبة.',
    emp_errShiftEnd: 'نهاية الوردية مطلوبة.',
    emp_errSalary: 'المرتب لازم يكون رقم أكبر من أو يساوي صفر.',
    emp_errSave: 'حصل خطأ أثناء حفظ الموظف.',
    emp_confirmTerminate: 'إنهاء خدمة الموظف ده؟ بيانات المرتبات والحضور القديمة بتاعته هتفضل محفوظة.',
    emp_status_terminated: 'انتهت خدمته',
    emp_terminate: 'إنهاء',
    emp_editEmployee: 'تعديل موظف',
    emp_addEmployee: 'إضافة موظف',
    emp_salary: 'المرتب',
    emp_saving: 'جاري الحفظ…',
    emp_save: 'حفظ',
    att_view: 'عرض',
    att_checkIn: 'الحضور',
    att_checkOut: 'الانصراف',
    att_hours: 'الساعات',
    att_late: 'التأخير',
    att_earlyLeave: 'انصراف مبكر',
    att_overtime: 'الإضافي',
    att_logBtn: '+ تسجيل حضور',
    att_daysPresent: 'أيام الحضور',
    att_daysLate: 'أيام التأخير',
    att_daysAbsent: 'أيام الغياب',
    att_totalHours: 'إجمالي الساعات',
    att_filterRange: 'فلترة بالتاريخ:',
    att_to: 'إلى',
    att_thisWeek: 'الأسبوع ده',
    att_fullMonth: 'الشهر كله',
    att_search: 'ابحث باسم الموظف أو رقم البصمة...',
    att_back: '→ رجوع',
    att_noRecords: 'مفيش حضور مسجل في الفترة دي.',
    att_monthlyCalendar: 'التقويم الشهري',
    att_noEmployees: 'مفيش موظفين.',
    att_logTitle: 'تسجيل حضور',
    att_employee: 'الموظف',
    att_selectEmployee: 'اختار الموظف',
    att_date: 'التاريخ',
    att_status: 'الحالة',
    att_hoursWorked: 'ساعات الشغل',
    att_lateMin: 'التأخير (دقايق)',
    att_earlyMin: 'الانصراف المبكر (دقايق)',
    att_overtimeMin: 'الإضافي (دقايق)',
    att_notes: 'ملاحظات',
    att_cancel: 'إلغاء',
    todayCheckInOut: 'النهارده (حضور / انصراف)',
    att_status_present: 'حاضر',
    att_status_late: 'متأخر',
    att_status_absent: 'غايب',
    'att_status_half-day': 'نص يوم',
    att_noRecord: 'مفيش تسجيل',
    att_inferredAbsence: 'غياب محسوب (مفيش تسجيل حضور)',
    att_title: 'الحضور والانصراف',
    att_subtitle: 'متابعة حضور الموظفين اليومي',
    loan_employee: 'الموظف',
    loan_status: 'الحالة',
    loan_created: 'تاريخ القرض',
    loan_actions: 'إجراءات',
    loan_edit: 'تعديل',
    loan_title: 'السلف والقروض',
    loan_subtitle: 'تسجيل ومتابعة سلف الموظفين وسدادها',
    loan_showFinished: 'عرض القروض المنتهية',
    loan_addBtn: '+ إضافة سلفة',
    loan_selectEmployee: 'اختار الموظف',
    loan_principalAmount: 'مبلغ السلفة',
    loan_remainingAmount: 'المتبقي',
    loan_installmentAmount: 'القسط الأسبوعي',
    loan_active: 'سارية',
    loan_closed: 'مقفولة',
    loan_cancel: 'إلغاء',
    loan_errEmployee: 'اختار الموظف.',
    loan_errPrincipal: 'مبلغ السلفة لازم يكون أكبر من صفر.',
    loan_errInstallment: 'القسط لازم يكون أكبر من صفر.',
    loan_errRemaining: 'المتبقي لازم يكون رقم أكبر من أو يساوي صفر.',
    loan_errUpdate: 'حصل خطأ أثناء تعديل السلفة.',
    loan_errCreate: 'حصل خطأ أثناء إضافة السلفة.',
    loan_principal: 'مبلغ السلفة',
    loan_remaining: 'المتبقي',
    loan_installment: 'القسط الأسبوعي',
    loan_finished: 'منتهية',
    loan_editTitle: 'تعديل سلفة',
    loan_addTitle: 'إضافة سلفة',
    loan_saving: 'جاري الحفظ…',
    loan_update: 'تحديث',
    loan_save: 'حفظ',
    nav_logout: 'تسجيل خروج',
    accounting: 'الحسابات',
    auth_email: 'البريد الإلكتروني',
    auth_password: 'كلمة المرور',
    prod_search: 'ابحث بالاسم أو الوصف...',
    nonNegativePrice: 'السعر لازم يكون رقم أكبر من أو يساوي صفر.',
    productUpdated: 'تم تعديل المنتج!',
    productAdded: 'تم إضافة المنتج!',
    failedSaveProduct: 'حصل خطأ أثناء حفظ المنتج.',
    deleteProduct: 'حذف المنتج ده؟',
    product: 'المنتج',
    description: 'الوصف',
    defaultPrice: 'السعر الافتراضي',
    manageProductCatalog: 'إدارة أسماء المنتجات للإنتاج والمبيعات',
    addProduct: '+ إضافة منتج',
    editProduct: 'تعديل منتج',
    cust_methodPh: 'مثال: كاش، تحويل، شيك',
    cust_refPh: 'رقم المرجع / الشيك',
    cust_name: 'الاسم',
    pay_employees: 'موظف',
    pay_more: 'كمان',
    pay_employeePayrolls: 'مرتب موظف',
    pay_vs: 'مقابل',
    selectWeekStart: 'اختار تاريخ بداية الأسبوع.',
    payrollPartialFail: 'اتعملت المرتبات بس فيه أخطاء في بعضها',
    payrollGenerated: 'اتعملت المرتبات لـ',
    payrollGeneratedOk: 'اتعملت المرتبات.',
    payrollGenerateFailed: 'حصل خطأ أثناء عمل المرتبات.',
    payrollPayFailed: 'حصل خطأ أثناء تسجيل الدفع.',
    payrollPayWeekFailed: 'حصل خطأ أثناء تسجيل دفع الأسبوع.',
    paid: 'مدفوع',
    pending: 'غير مدفوع',
    recalcDriftHint: 'الحساب الحالي مختلف عن المبلغ المدفوع',
    all: 'الكل',
    searchByName: 'ابحث بالاسم…',
    payrollTruncated: 'بيظهر آخر السجلات بس. ضيّق الفترة عشان تشوف كل حاجة.',
    noPayrollMatch: 'مفيش مرتبات مطابقة للفلتر ده.',
    noPayrollYet: 'لسه مفيش مرتبات. استخدم "+ إنشاء" عشان تعمل أول مرتب أسبوعي.',
    open: 'فتح',
    weekDate: 'تاريخ الأسبوع',
    weeklyPayrollHint: 'أسبوع المرتبات من السبت للجمعة. التاريخ اللي تختاره بيتحط في الأسبوع بتاعه، والمرتب بيتحسب من حضور الأسبوع ده. المكافآت والخصومات لكل موظف تقدر تضيفها بعدين من زرار "تعديل" في كل صف.',
    sal_search: 'ابحث برقم الأمر أو العميل أو الحالة أو حالة الدفع...',
    sal_orderNo: 'رقم الأمر',
    sal_selectCustomer: 'اختار العميل',
    sal_pay_paid: 'مدفوع',
    sal_pay_invoiced: 'مدفوع جزئياً',
    sal_pay_partially_paid: 'مدفوع جزئياً',
    sal_pay_pending: 'غير مدفوع',
    orderNumber: 'رقم الأمر',
    total: 'الإجمالي',
    defaultColor: 'افتراضي',
    productionMetrics: 'بيانات الإنتاج',
    inputQty: 'الكمية الداخلة',
    sortingQty: 'كمية الفرز',
    finalQty: 'الكمية النهائية',
    selectCustomer: 'اختار العميل.',
    orderItemsRequired: 'ضيف على الأقل أمر إنتاج واحد بسعر للقطعة.',
    noValidItems: 'مفيش أصناف صالحة في الأوامر المختارة.',
    createOrderFailed: 'حصل خطأ أثناء إنشاء الأمر.',
    updateStatusFailed: 'حصل خطأ أثناء تغيير الحالة.',
    details: 'التفاصيل',
    selectOrder: 'اختار الأمر',
    addOrder: '+ إضافة أمر',
    orderDetails: 'تفاصيل الأمر',
    failedToLoadOrderDetails: 'حصل خطأ أثناء تحميل تفاصيل الأمر',
    att_hUnit: 'ساعة',
    att_mUnit: 'د',
    noRecordsFound: 'لا توجد بيانات',
  },
};

const normalizeLanguage = (value) => {
  const lang = String(value || '').trim().toLowerCase();
  if (lang.startsWith('ar')) return 'ar';
  return 'en';
};

const initialLanguage = () => {
  if (!globalThis.window) return 'en';
  return normalizeLanguage(localStorage.getItem(LANG_STORAGE_KEY) || globalThis.window.navigator?.language || 'en');
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(initialLanguage);

  useEffect(() => {
    localStorage.setItem(LANG_STORAGE_KEY, language);
    setApiLanguage(language);
    if (globalThis.document) {
      globalThis.document.documentElement.lang = language;
      globalThis.document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    }
  }, [language]);

  const updateLanguage = (nextLanguage) => {
    setLanguage(normalizeLanguage(nextLanguage));
  };

  const t = (key, fallback = '') => {
    const entry = translations[language]?.[key];
    if (typeof entry === 'function') return entry(fallback);
    return entry || fallback || key;
  };

  const value = useMemo(() => ({ language, setLanguage: updateLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
