/* eslint-disable react/prop-types */
import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { setApiLanguage } from '../api';

const LANG_STORAGE_KEY = 'lang';

const translations = {
  en: {
    appName: 'FabriCore',
    appSubtitle: 'Factory Management',
    main: 'Main',
    operations: 'Operations',
    people: 'People',
    business: 'Business',
    dashboard: 'Dashboard',
    production: 'Production',
    createOrder: 'Create Order',
    sorting: 'Sorting (فرز)',
    finalPhase: 'Final Phase',
    prodReport: 'Production Report',
    productionPipeline: 'Pipeline Kanban',
    productionPipelineSubtitle: 'Drag and drop production orders across stages',
    noOrders: 'No orders in this stage',
    products: 'Products',
    inventory: 'Inventory',
    employees: 'Employees',
    attendance: 'Attendance',
    payroll: 'Payroll',
    loans: 'Loans',
    sales: 'Sales',
    customers: 'Customers',
    reports: 'Reports',
    signIn: 'Sign in',
    welcomeBack: 'Welcome back. Enter your credentials to continue.',
    loginHint: 'Factory Management',
    dashboardDate: (date) => date,
    activeOrders: 'Active orders',
    currentlyOpen: 'Currently open',
    revenue: 'Revenue',
    customerPaymentsThisMonth: 'Customer payments this month',
    moneySpent: 'Money spent',
    paidPayrollThisMonth: 'Paid payroll this month',
    netAfterPayroll: 'Net after payroll',
    revenueMinusPaidSalary: 'Revenue minus paid salary',
    productionByStatus: 'Production by status',
    noProductionDataYet: 'No production data yet',
    quickStats: 'Quick stats',
    lowStockItems: 'Low stock items',
    activeEmployees: 'Active employees',
    paidPayrollThisMonthShort: 'Paid payroll this month',
    selectLanguage: 'Language',
    english: 'EN',
    arabic: 'العربية',
    unit: 'Unit',
    email: 'Email',
    phone: 'Phone',
    city: 'City',
    country: 'Country',
    address: 'Address',
    since: 'Since',
    payment: 'Payment',
    new: 'New',
    confirmed: 'Confirmed',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    view: 'View',
    ledger: 'Ledger',
    close: 'Close',
    delete: 'Delete',
    addItem: '+ Add item',
    remove: 'Remove',
    generate: 'Generate',
    manageRawMaterials: 'Manage raw materials and stock levels',
    material: 'Material',
    category: 'Category',
    qty: 'Qty',
    minQty: 'Min qty',
    unitCost: 'Unit cost',
    supplier: 'Supplier',
    status: 'Status',
    addMaterial: 'Add material',
    editMaterial: 'Edit material',
    save: 'Save',
    cancel: 'Cancel',
    saving: 'Saving…',
    lowStock: 'Low stock',
    ok: 'OK',
    edit: 'Edit',
    del: 'Del',
    nameRequired: 'Name is required.',
    unitRequired: 'Unit is required.',
    nonNegativeQuantity: 'Quantity must be a non-negative number.',
    nonNegativeMinQuantity: 'Min quantity must be a non-negative number.',
    failedSaveMaterial: 'Failed to save material.',
    deleteMaterial: 'Delete this material?',
    materialUpdated: 'Material updated!',
    materialAdded: 'Material added!',
    addCustomer: 'Add customer',
    customerNameRequired: 'Customer name is required.',
    validEmailRequired: 'A valid email is required.',
    phoneRequired: 'Phone is required.',
    customerAdded: 'Customer added successfully!',
    failedAddCustomer: 'Failed to add customer.',
    customerLedger: 'Customer ledger',
    productsTaken: 'Products taken',
    totalOrdered: 'Total ordered',
    totalPaid: 'Total paid',
    remaining: 'Remaining',
    paymentDate: 'Payment date',
    amount: 'Amount',
    notes: 'Notes',
    addPayment: 'Add payment',
    evidence: 'Evidence',
    viewFile: 'View file',
    noOrdersYet: 'No orders for this customer yet.',
    noPaymentsYet: 'No payments recorded yet.',
    manageClientAccounts: 'Manage your client accounts',
    savePolicy: 'Save Policy',
    attendancePayrollPolicy: 'Attendance & Payroll Policy',
    configurePolicy: 'Configure grace period, multipliers, and weekly payment estimate',
    lateGraceMinutes: 'Late Grace Minutes',
    regularOvertimeMultiplier: 'Regular Overtime Multiplier',
    vacationWeekendMultiplier: 'Vacation/Weekend Multiplier',
    weeksPerMonth: 'Weeks Per Month',
    lateGraceRange: 'Late grace minutes must be between 0 and 180.',
    overtimeRange: 'Overtime multiplier must be between 1 and 5.',
    vacationRange: 'Vacation multiplier must be between 0 and 5.',
    weeksRange: 'Weeks per month must be between 1 and 6.',
    settingsSaved: 'Settings saved successfully. New values apply immediately.',
    failedLoadSettings: 'Failed to load settings',
    failedSaveSettings: 'Failed to save settings',
    createProductionOrder: 'Create Production Order',
    inputPhaseMaterialConsumption: 'Input phase + material consumption',
    modelNumber: 'Model Number',
    productNumber: 'Product Number',
    productName: 'Product Name',
    productNumberRequired: 'Product number is required.',
    productNameRequired: 'Product name is required.',
    productNumberPlaceholder: 'e.g. 6001, 6002',
    selectProductRequired: 'Please select a product.',
    createOrderSubtitle: 'Select product name and enter the order number (e.g. 6001, 6002)',
    productNamePlaceholder: 'Product name',
    sortingSubtitle: 'Record sorting quantity for each production order',
    sortingSaved: 'Sorting phase saved.',
    exitPermissionInManage: 'Print exit permission from Manage Orders.',
    printExitPermission: 'Exit Permission',
    reprintExitPermission: 'Reprint Exit Permission',
    printing: 'Printing…',
    printFailed: 'Failed to print exit permission.',
    manageOrders: 'Manage Orders',
    manageOrdersSubtitle: 'View orders, print exit permission after sorting, or cancel with password',
    cancelOrder: 'Cancel / Delete',
    cancelOrderTitle: 'Cancel Production Order?',
    cancelOrderWarning: 'This will permanently delete the order and restore deducted materials. Finished product stock will be reversed if applicable.',
    confirmPassword: 'Enter your password to confirm',
    passwordRequired: 'Password is required.',
    orderDeleted: 'Order cancelled and deleted successfully.',
    allStatuses: 'All statuses',
    plannedQuantity: 'Planned Quantity',
    materials: 'Materials',
    qtyUsed: 'Qty used',
    lastCreatedOrder: 'Last Created Order',
    phase: 'Phase',
    quantity: 'Quantity',
    trackManufacturingOrders: 'Track manufacturing orders and progress',
    newOrder: '+ New order',
    allStatuses: 'All statuses',
    newProductionOrder: 'New production order',
    productName: 'Product name',
    assignTo: 'Assign to',
    startDate: 'Start date',
    dueDate: 'Due date',
    newOrderSaved: 'Creating…',
    createOrderButton: 'Create order',
    updateProgress: 'Update progress',
    orderedQuantity: 'Ordered quantity',
    finishedQuantity: 'Finished quantity',
    saveProgress: 'Save progress',
    progress: 'Progress',
    productionTrackingReport: 'Production Tracking Report',
    comparePhases: 'Compare quantities across Input, Sorting, and Final phases',
    selectProductionOrder: 'Select Production Order',
    chooseOrder: 'Choose order',
    metric: 'Metric',
    value: 'Value',
    phaseDetails: 'Phase Details',
    phaseQuantityChart: 'Phase Quantity Chart',
    alerts: 'Alerts',
    warningLoss: 'Warning: Loss exceeds 10% (HIGH_LOSS alert)',
    efficiency: 'Efficiency',
    loss: 'Loss',
    input: 'Input',
    final: 'Final',
    totalLoss: 'Total Loss',
    lossPercentage: 'Loss Percentage',
    trackDailyAttendance: 'Track daily employee attendance',
    logAttendance: 'Log attendance',
    daysPresent: 'Days present',
    daysLate: 'Days late',
    daysAbsent: 'Days absent',
    totalHours: 'Total hours',
    back: 'Back',
    monthlyCalendar: 'Monthly calendar',
    noRecordsForMonth: 'No attendance records for this month.',
    noEmployeesFound: 'No employees found.',
    employee: 'Employee',
    present: 'Present',
    late: 'Late',
    absent: 'Absent',
    deviceNo: 'Device No',
    attendanceRate: 'Attendance rate',
    checkIn: 'Check in',
    checkOut: 'Check out',
    hoursWorked: 'Hours worked',
    earlyLeave: 'Early leave',
    overtime: 'Overtime',
    date: 'Date',
    statusLabel: 'Status',
    selectEmployee: 'Select employee',
    selectMaterial: 'Select material',
    logAttendanceButton: '+ Log attendance',
    manageCustomerOrders: 'Manage customer orders and invoices',
    newSalesOrder: 'New sales order',
    orderItems: 'Order items',
    productNamePlaceholder: 'Product name',
    qtyPlaceholder: 'Qty',
    unitPricePlaceholder: 'Unit price',
    create: 'Create',
    customerBalance: 'Customer balance',
    clear: 'Clear',
    orderStatus: 'Order status',
    weeklyPayroll: 'Manage weekly payroll (Saturday to Friday) and payments',
    weekStartSaturday: 'Week start (Saturday)',
    generatePayroll: 'Generate payroll',
    payrollBreakdown: 'Payroll breakdown',
    markAsPaid: 'Mark as paid?',
    markPaid: 'Mark paid',
    week: 'Week',
    role: 'Role',
    base: 'Base',
    bonus: 'Bonus',
    deductions: 'Deductions',
    netSalary: 'Net salary',
    weeklyPay: 'Weekly pay',
    breakdown: 'Breakdown',
    autoBonus: 'Auto bonus',
    autoDeductions: 'Auto deductions',
    manualBonus: 'Manual bonus',
    manualDeductions: 'Manual deductions',
    clearManual: 'Clear manual',
    confirmClearManual: 'Clear manual bonus and deductions for this employee?',
    lateMinutes: 'Late minutes',
    lateWeightedMinutes: 'Late weighted minutes',
    earlyLeaveMinutes: 'Early leave minutes',
    regularOvertime: 'Regular overtime',
    weekendWorkOvertime: 'Weekend work overtime',
    totalOvertime: 'Total overtime',
    absentDays: 'Absent days',
    halfDays: 'Half days',
    inferredAbsentDays: 'Inferred absent days',
    weeklyPaymentEstimate: 'Weekly payment estimate',
    lateDeduction: 'Late',
    weighted: 'weighted',
    days: 'day(s)',
    halfDay: 'Half day',
    hrBonus: 'HR bonus',
    hrPenalty: 'HR penalty',
    hrOvertime: 'HR overtime',
    noAdjustments: 'No deductions or bonuses this week.',
    machine: 'Machine',
    partnerFactory: 'Partner Factory',
    selectPartnerFactory: 'Select partner factory',
    addPartnerFactory: '+ Add partner factory',
    partnerFactoryName: 'Factory name',
    partnerFactoryNameRequired: 'Partner factory name is required.',
    partnerFactoryCreateFailed: 'Failed to add partner factory.',
    contactPerson: 'Contact person',
    phone: 'Phone',
    machineOrPartnerFactory: 'Machine / Partner Factory',
    duration: 'Duration',
    deleteOrder: 'Delete Production Order?',
    deleteWarning: 'This will delete the production order and restore all deducted inventory. This action cannot be undone.',
    deleteFailed: 'Failed to delete order',
    deleteFailedCycleStarted: 'Cannot delete order - sorting or final phase has already started. You can only delete new orders.',
    deleting: 'Deleting...',
    outsourcing: 'Outsourcing',
    outsourcingPhase: 'Outsourcing Phase',
    outsourcingSubtitle: 'Send items to an external partner factory for specialized processing',
    outsourcingQty: 'Outsourcing Quantity',
    outsourcingQtyError: 'Outsourcing quantity must be a non-negative integer.',
    outsourcingSaved: 'Outsourcing phase saved.',
    outsourcingFailed: 'Failed to save outsourcing phase.',
    outsourcingSaveBtn: 'Save Outsourcing Phase',
    stageEfficiency: 'Stage Efficiency',
    totalQty: 'Total Qty',
    avgLoss: 'Avg Loss %',
    currentOrders: 'Current Orders',
    adjust: 'Adjust',
    adjustPayroll: 'Adjust Payroll',
    failedAdjustPayroll: 'Failed to adjust payroll.',
    loanDeduction: 'Loan deduction',
    weekDateRange: 'Week date range',
    from: 'from',
    to: 'to',
    saturday: 'Saturday',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    confirmDeleteWeekPayroll: "Are you sure you want to delete this week's payroll? This will also revert any loan deductions applied for this week.",
    payrollDeleteFailed: 'Failed to delete payroll week.',
    exportPDF: 'Export PDF',
    payrollExportFailed: 'Failed to export payroll to PDF.',
    totalNet: 'Total Net',
    department: 'Department',
  },
  ar: {
    appName: 'فابري كور',
    appSubtitle: 'إدارة المصنع',
    main: 'الرئيسية',
    operations: 'العمليات',
    people: 'الأفراد',
    business: 'الأعمال',
    dashboard: 'لوحة التحكم',
    production: 'الإنتاج',
    createOrder: 'إنشاء أمر',
    sorting: 'الفرز',
    finalPhase: 'المرحلة النهائية',
    prodReport: 'تقرير الإنتاج',
    productionPipeline: 'مراحل الإنتاج (كانبان)',
    productionPipelineSubtitle: 'سحب وإفلات أوامر الإنتاج بين المراحل',
    noOrders: 'لا توجد طلبات في هذه المرحلة',
    products: 'المنتجات',
    inventory: 'المخزون',
    employees: 'الموظفون',
    attendance: 'الحضور',
    payroll: 'الرواتب',
    loans: 'القروض',
    sales: 'المبيعات',
    customers: 'العملاء',
    reports: 'التقارير',
    signIn: 'تسجيل الدخول',
    welcomeBack: 'مرحباً بعودتك. أدخل بياناتك للمتابعة.',
    loginHint: 'إدارة المصنع',
    dashboardDate: (date) => date,
    activeOrders: 'الطلبات النشطة',
    currentlyOpen: 'المفتوحة حالياً',
    revenue: 'الإيرادات',
    customerPaymentsThisMonth: 'مدفوعات العملاء هذا الشهر',
    moneySpent: 'المصروف',
    paidPayrollThisMonth: 'الرواتب المدفوعة هذا الشهر',
    netAfterPayroll: 'الصافي بعد الرواتب',
    revenueMinusPaidSalary: 'الإيرادات ناقص الرواتب المدفوعة',
    productionByStatus: 'الإنتاج حسب الحالة',
    noProductionDataYet: 'لا توجد بيانات إنتاج بعد',
    quickStats: 'إحصاءات سريعة',
    lowStockItems: 'العناصر منخفضة المخزون',
    activeEmployees: 'الموظفون النشطون',
    paidPayrollThisMonthShort: 'الرواتب المدفوعة هذا الشهر',
    selectLanguage: 'اللغة',
    english: 'EN',
    arabic: 'العربية',
    unit: 'الوحدة',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    city: 'المدينة',
    country: 'الدولة',
    address: 'العنوان',
    since: 'منذ',
    payment: 'الدفع',
    new: 'جديد',
    confirmed: 'مؤكد',
    shipped: 'تم الشحن',
    delivered: 'تم التسليم',
    cancelled: 'ملغي',
    view: 'عرض',
    ledger: 'كشف الحساب',
    close: 'إغلاق',
    delete: 'حذف',
    addItem: '+ إضافة عنصر',
    remove: 'إزالة',
    generate: 'توليد',
    manageRawMaterials: 'إدارة المواد الخام ومستويات المخزون',
    C: 'المادة',
    category: 'الفئة',
    qty: 'الكمية',
    minQty: 'الحد الأدنى',
    unitCost: 'تكلفة الوحدة',
    supplier: 'المورّد',
    status: 'الحالة',
    addMaterial: 'إضافة مادة',
    editMaterial: 'تعديل مادة',
    save: 'حفظ',
    cancel: 'إلغاء',
    saving: 'جارٍ الحفظ…',
    lowStock: 'مخزون منخفض',
    ok: 'ممتاز',
    edit: 'تعديل',
    del: 'حذف',
    nameRequired: 'الاسم مطلوب.',
    unitRequired: 'الوحدة مطلوبة.',
    nonNegativeQuantity: 'يجب أن تكون الكمية رقماً غير سالب.',
    nonNegativeMinQuantity: 'يجب أن يكون الحد الأدنى رقماً غير سالب.',
    failedSaveMaterial: 'فشل حفظ المادة.',
    deleteMaterial: 'حذف هذه المادة؟',
    materialUpdated: 'تم تحديث المادة!',
    materialAdded: 'تمت إضافة المادة!',
    addCustomer: 'إضافة عميل',
    customerNameRequired: 'اسم العميل مطلوب.',
    validEmailRequired: 'البريد الإلكتروني الصحيح مطلوب.',
    phoneRequired: 'رقم الهاتف مطلوب.',
    customerAdded: 'تمت إضافة العميل بنجاح!',
    failedAddCustomer: 'فشل إضافة العميل.',
    customerLedger: 'حساب العميل',
    productsTaken: 'المنتجات المسحوبة',
    totalOrdered: 'إجمالي الطلب',
    totalPaid: 'إجمالي المدفوع',
    remaining: 'المتبقي',
    paymentDate: 'تاريخ الدفع',
    amount: 'المبلغ',
    notes: 'ملاحظات',
    addPayment: 'إضافة دفعة',
    evidence: 'الإثبات',
    viewFile: 'عرض الملف',
    noOrdersYet: 'لا توجد طلبات لهذا العميل بعد.',
    noPaymentsYet: 'لم يتم تسجيل أي دفعات بعد.',
    manageClientAccounts: 'إدارة حسابات العملاء',
    savePolicy: 'حفظ السياسة',
    attendancePayrollPolicy: 'سياسة الحضور والرواتب',
    configurePolicy: 'تحديد فترة السماح والمعاملات وتقدير الدفع الأسبوعي',
    lateGraceMinutes: 'دقائق السماح للتأخير',
    regularOvertimeMultiplier: 'معامل الوقت الإضافي العادي',
    vacationWeekendMultiplier: 'معامل الإجازة/الويكند',
    weeksPerMonth: 'أسابيع الشهر',
    lateGraceRange: 'يجب أن تكون دقائق السماح بين 0 و180.',
    overtimeRange: 'يجب أن يكون معامل الوقت الإضافي بين 1 و5.',
    vacationRange: 'يجب أن يكون معامل الإجازة بين 0 و5.',
    weeksRange: 'يجب أن تكون أسابيع الشهر بين 1 و6.',
    settingsSaved: 'تم حفظ الإعدادات بنجاح. القيم الجديدة تطبق فوراً.',
    failedLoadSettings: 'فشل تحميل الإعدادات',
    failedSaveSettings: 'فشل حفظ الإعدادات',
    createProductionOrder: 'إنشاء أمر إنتاج',
    inputPhaseMaterialConsumption: 'مرحلة الإدخال + استهلاك المواد',
    modelNumber: 'رقم الموديل',
    productNumber: 'رقم المنتج',
    productName: 'اسم المنتج',
    productNumberRequired: 'رقم المنتج مطلوب.',
    productNameRequired: 'اسم المنتج مطلوب.',
    productNumberPlaceholder: 'مثال: 6001، 6002',
    selectProductRequired: 'يرجى اختيار المنتج.',
    createOrderSubtitle: 'اختر اسم المنتج وأدخل رقم الطلب (مثال: 6001، 6002)',
    productNamePlaceholder: 'اسم المنتج',
    sortingSubtitle: 'تسجيل كمية الفرز لكل أمر إنتاج',
    sortingSaved: 'تم حفظ مرحلة الفرز.',
    exitPermissionInManage: 'اطبع إذن الخروج من صفحة إدارة الطلبات.',
    printExitPermission: 'إذن الخروج',
    reprintExitPermission: 'إعادة طباعة إذن الخروج',
    printing: 'جاري الطباعة…',
    printFailed: 'فشل طباعة إذن الخروج.',
    manageOrders: 'إدارة الطلبات',
    manageOrdersSubtitle: 'عرض الطلبات وطباعة إذن الخروج بعد الفرز أو الإلغاء بكلمة المرور',
    cancelOrder: 'إلغاء / حذف',
    cancelOrderTitle: 'إلغاء أمر الإنتاج؟',
    cancelOrderWarning: 'سيؤدي هذا إلى حذف الطلب نهائياً واستعادة المواد المخصومة. سيتم عكس مخزون المنتجات النهائية إن وُجد.',
    confirmPassword: 'أدخل كلمة المرور للتأكيد',
    passwordRequired: 'كلمة المرور مطلوبة.',
    orderDeleted: 'تم إلغاء الطلب وحذفه بنجاح.',
    allStatuses: 'كل الحالات',
    plannedQuantity: 'الكمية المخططة',
    materials: 'المواد',
    qtyUsed: 'الكمية المستخدمة',
    lastCreatedOrder: 'آخر أمر تم إنشاؤه',
    phase: 'المرحلة',
    quantity: 'الكمية',
    trackManufacturingOrders: 'متابعة أوامر التصنيع والتقدم',
    newOrder: '+ أمر جديد',
    allStatuses: 'كل الحالات',
    newProductionOrder: 'أمر إنتاج جديد',
    productName: 'اسم المنتج',
    assignTo: 'إسناد إلى',
    startDate: 'تاريخ البداية',
    dueDate: 'تاريخ الاستحقاق',
    newOrderSaved: 'جارٍ الإنشاء…',
    createOrderButton: 'إنشاء الطلب',
    updateProgress: 'تحديث التقدم',
    orderedQuantity: 'الكمية المطلوبة',
    finishedQuantity: 'الكمية المنجزة',
    saveProgress: 'حفظ التقدم',
    progress: 'التقدم',
    productionTrackingReport: 'تقرير تتبع الإنتاج',
    comparePhases: 'مقارنة الكميات بين الإدخال والفرز والنهائي',
    selectProductionOrder: 'اختيار أمر الإنتاج',
    chooseOrder: 'اختيار الأمر',
    metric: 'المؤشر',
    value: 'القيمة',
    phaseDetails: 'تفاصيل المراحل',
    phaseQuantityChart: 'مخطط كميات المراحل',
    alerts: 'التنبيهات',
    warningLoss: 'تحذير: الفاقد يتجاوز 10% (تنبيه HIGH_LOSS)',
    efficiency: 'الكفاءة',
    loss: 'الفاقد',
    input: 'الإدخال',
    final: 'النهائي',
    totalLoss: 'إجمالي الفاقد',
    lossPercentage: 'نسبة الفاقد',
    trackDailyAttendance: 'متابعة حضور الموظفين يومياً',
    logAttendance: 'تسجيل الحضور',
    daysPresent: 'أيام الحضور',
    daysLate: 'أيام التأخير',
    daysAbsent: 'أيام الغياب',
    totalHours: 'إجمالي الساعات',
    back: 'رجوع',
    monthlyCalendar: 'التقويم الشهري',
    noRecordsForMonth: 'لا توجد سجلات حضور لهذا الشهر.',
    noEmployeesFound: 'لم يتم العثور على موظفين.',
    employee: 'الموظف',
    present: 'حاضر',
    late: 'متأخر',
    absent: 'غائب',
    deviceNo: 'رقم الجهاز',
    attendanceRate: 'نسبة الحضور',
    checkIn: 'الدخول',
    checkOut: 'الخروج',
    hoursWorked: 'ساعات العمل',
    earlyLeave: 'انصراف مبكر',
    overtime: 'إضافي',
    date: 'التاريخ',
    statusLabel: 'الحالة',
    selectEmployee: 'اختيار الموظف',
    logAttendanceButton: '+ تسجيل حضور',
    manageCustomerOrders: 'إدارة طلبات العملاء والفواتير',
    newSalesOrder: 'طلب مبيعات جديد',
    orderItems: 'عناصر الطلب',
    productNamePlaceholder: 'اسم المنتج',
    qtyPlaceholder: 'الكمية',
    unitPricePlaceholder: 'سعر الوحدة',
    create: 'إنشاء',
    customerBalance: 'رصيد العميل',
    clear: 'صفر',
    orderStatus: 'حالة الطلب',
    weeklyPayroll: 'إدارة الرواتب الأسبوعية (من السبت إلى الجمعة) والمدفوعات',
    weekStartSaturday: 'بداية الأسبوع (السبت)',
    generatePayroll: 'توليد الرواتب',
    payrollBreakdown: 'تفصيل الراتب',
    markAsPaid: 'تحديد كمدفوع؟',
    markPaid: 'تم الدفع',
    week: 'الأسبوع',
    role: 'الوظيفة',
    base: 'الأساسي',
    bonus: 'البدل',
    deductions: 'الاستقطاعات',
    netSalary: 'صافي الراتب',
    weeklyPay: 'الأجر الأسبوعي',
    breakdown: 'التفصيل',
    autoBonus: 'سهر',
    autoDeductions: 'خصومات تأخير',
    manualBonus: 'بدل يدوي',
    manualDeductions: 'جزاءات',
    clearManual: 'مسح اليدوي',
    confirmClearManual: 'هل تريد مسح البدل اليدوي والجزاءات لهذا الموظف؟',
    lateMinutes: 'دقائق التأخير',
    lateWeightedMinutes: 'دقائق التأخير الموزونة',
    earlyLeaveMinutes: 'دقائق الانصراف المبكر',
    regularOvertime: 'الوقت الإضافي العادي',
    weekendWorkOvertime: 'إضافي نهاية الأسبوع',
    totalOvertime: 'إجمالي الإضافي',
    absentDays: 'أيام الغياب',
    halfDays: 'أنصاف الأيام',
    inferredAbsentDays: 'أيام غياب مستنتجة',
    weeklyPaymentEstimate: 'تقدير الدفع الأسبوعي',
    lateDeduction: 'التأخير',
    weighted: 'موزونة',
    days: 'يوم',
    halfDay: 'نصف يوم',
    hrBonus: 'مكافأة (موارد بشرية)',
    hrPenalty: 'جزاء (موارد بشرية)',
    hrOvertime: 'إضافي (موارد بشرية)',
    noAdjustments: 'لا يوجد خصومات أو مكافآت هذا الأسبوع.',
    machine: 'الماكينة',
    partnerFactory: 'المصنع الشريك',
    selectPartnerFactory: 'اختر المصنع الشريك',
    addPartnerFactory: '+ إضافة مصنع شريك',
    partnerFactoryName: 'اسم المصنع',
    partnerFactoryNameRequired: 'اسم المصنع الشريك مطلوب.',
    partnerFactoryCreateFailed: 'فشل إضافة المصنع الشريك.',
    contactPerson: 'جهة الاتصال',
    phone: 'الهاتف',
    machineOrPartnerFactory: 'الماكينة / المصنع الشريك',
    duration: 'المدة',
    deleteOrder: 'حذف أمر الإنتاج؟',
    deleteWarning: 'سيؤدي هذا إلى حذف أمر الإنتاج واستعادة جميع المخزون المخصوم. لا يمكن التراجع عن هذا الإجراء.',
    deleteFailed: 'فشل حذف الطلب',
    deleteFailedCycleStarted: 'لا يمكن حذف الطلب - مرحلة الفرز أو النهائية قد بدأت بالفعل. يمكنك فقط حذف الطلبات الجديدة.',
    deleting: 'جاري الحذف...',
    outsourcing: 'التعهيد',
    outsourcingPhase: 'مرحلة التعهيد',
    outsourcingSubtitle: 'إرسال العناصر إلى مصنع شريك خارجي للمعالجة المتخصصة',
    outsourcingQty: 'كمية التعهيد',
    outsourcingQtyError: 'يجب أن تكون كمية التعهيد رقماً غير سالب.',
    outsourcingSaved: 'تم حفظ مرحلة التعهيد.',
    outsourcingFailed: 'فشل حفظ مرحلة التعهيد.',
    outsourcingSaveBtn: 'حفظ مرحلة التعهيد',
    stageEfficiency: 'كفاءة المراحل',
    totalQty: 'إجمالي الكمية',
    avgLoss: 'متوسط الفاقد %',
    currentOrders: 'الطلبات الحالية',
    adjust: 'تعديل',
    adjustPayroll: 'تعديل الراتب',
    failedAdjustPayroll: 'فشل تعديل الراتب.',
    loanDeduction: 'سلف',
    weekDateRange: 'فترة الأسبوع',
    from: 'من',
    to: 'إلى',
    saturday: 'السبت',
    sunday: 'الأحد',
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednesday: 'الأربعاء',
    thursday: 'الخميس',
    friday: 'الجمعة',
    confirmDeleteWeekPayroll: 'هل أنت متأكد من حذف راتب هذا الأسبوع؟ سيؤدي هذا أيضاً إلى إلغاء أي استقطاعات للقروض تم تطبيقها لهذا الأسبوع.',
    payrollDeleteFailed: 'فشل حذف راتب الأسبوع.',
    exportPDF: 'تصدير PDF',
    payrollExportFailed: 'فشل تصدير كشف الرواتب إلى PDF.',
    totalNet: 'إجمالي الصافي',
    department: 'القسم',
  },
};

const normalizeLanguage = (value) => {
  const lang = String(value || '').trim().toLowerCase();
  if (lang.startsWith('ar')) return 'ar';
  return 'en';
};

const initialLanguage = () => {
  if (!globalThis.window) return 'en';
  return normalizeLanguage(localStorage.getItem(LANG_STORAGE_KEY) || globalThis.window.navigator?.language || 'en');
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(initialLanguage);

  useEffect(() => {
    localStorage.setItem(LANG_STORAGE_KEY, language);
    setApiLanguage(language);
    if (globalThis.document) {
      globalThis.document.documentElement.lang = language;
      globalThis.document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    }
  }, [language]);

  const updateLanguage = (nextLanguage) => {
    setLanguage(normalizeLanguage(nextLanguage));
  };

  const t = (key, fallback = '') => {
    const entry = translations[language]?.[key];
    if (typeof entry === 'function') return entry(fallback);
    return entry || fallback || key;
  };

  const value = useMemo(() => ({ language, setLanguage: updateLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
