const express = require('express');
const router = express.Router();

const authRoutes = require('../modules/auth/auth.routes');
const dashboardRoutes = require('../modules/dashboard/dashboard.routes');
const reportsRoutes = require('../modules/reports/reports.routes');
const inventoryRoutes = require('../modules/inventory/inventory.routes');
const employeeRoutes = require('../modules/employees/employee.routes');
const payrollRoutes = require('./payroll.routes');
const productRoutes = require('../modules/products/product.routes');
const settingsRoutes = require('../modules/settings/settings.routes');
const salesRoutes = require('../modules/sales/sales.routes');
const productionRoutes = require('../modules/production/production.routes');
const productionTrackingRoutes = require('../modules/productionTracking/productionTracking.routes');
const purchasingRoutes = require('../modules/purchasing/purchasing.routes');
const manufacturingRoutes = require('../modules/manufacturing/manufacturing.routes');
const qcRoutes = require('../modules/qc/qc.routes');
const hrRoutes = require('../modules/hr/hr.routes');
const accountingRoutes = require('../modules/accounting/accounting.routes');
const printShopRoutes = require('../modules/printShop/printShop.routes');
const productionCycleRoutes = require('../modules/productionCycle/productionCycle.routes');

router.use('/', authRoutes);
router.use('/', dashboardRoutes);
router.use('/', employeeRoutes);
router.use('/', salesRoutes);
router.use('/', productRoutes);
router.use('/', productionRoutes);
router.use('/', productionTrackingRoutes);
router.use('/', printShopRoutes);
router.use('/', productionCycleRoutes);
router.use('/', payrollRoutes);
router.use('/', qcRoutes);
router.use('/', reportsRoutes);
router.use('/', settingsRoutes);
router.use('/', inventoryRoutes);
router.use('/purchasing', purchasingRoutes);
router.use('/manufacturing', manufacturingRoutes);
router.use('/hr', hrRoutes);
router.use('/accounting', accountingRoutes);

module.exports = router;
